version: '3.7'

services:

  php-app:
    build: 
      context: .
    ports:
      - "9001:80"
    container_name: web_app
    networks:
      - php-net

  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: e_learning
      MYSQL_USER: ismail
      MYSQL_PASSWORD: password1
    ports:
      - "3306:3306"
    networks:
      - php-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php_myadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password1
    ports:
      - "8080:80"
    networks:
      - php-net
    

networks:
  php-net:
    driver: bridge
